# Welcome to ISCRI notebook

ISCRI notebook

## Metrics

Show metrics from the database

## Jupyter code

You can modify the code
To enable the code completion, simply hit the Tab key while writing code. This will open a menu with suggestions.

Cyril Vincent for Skema Business School
0622538762
contact@cyrilvincent.com

In [1]:
import sys
import sqlalchemy
import config
import pandas as pd
import art
from dbcontext import Context
from jupyter_service import JupyterService
art.tprint(config.name, "big")
print(sys.version, sqlalchemy.__version__, pd.__version__, config.version)

 _____   _____   _____  _____   _____
|_   _| / ____| / ____||  __ \ |_   _|
  | |  | (___  | |     | |__) |  | |
  | |   \___ \ | |     |  _  /   | |
 _| |_  ____) || |____ | | \ \  _| |_
|_____||_____/  \_____||_|  \_\|_____|



3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] 2.0.35 2.2.3 0.1.0.Alpha

In [2]:
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', None)
print(config.connection_string)
context = Context()
context.create(echo=False)
service = JupyterService(context)

postgresql://postgres:sa@localhost:5432/iscri

In [3]:
sql = "select * from event where global_event_id=420620763"
service.get_by_sql(sql)

select * from event where global_event_id=420620763

,id,global_event_id,date,month_year,year,gdelt_date,file_id,actor1_code,actor1_name,actor1_country_code,actor1_known_group_code,actor1_ethnic_code,actor1_religion1_code,actor1_religion2_code,actor1_type1_code,actor1_type2_code,actor1_type3_code,actor2_code,actor2_name,actor2_country_code,actor2_known_group_code,actor2_ethnic_code,actor2_religion1_code,actor2_religion2_code,actor2_type1_code,actor2_type2_code,actor2_type3_code,is_root_event,event_code,event_base_code,event_root_code,quad_class,goldstein_scale,num_mentions,num_sources,num_articles,avg_tone,actor1_geo_type,actor1_geo_fullname,actor1_geo_country_code,actor1_geo_adm1_code,actor1_geo_lat,actor1_geo_lon,actor1_feature_id,actor2_geo_type,actor2_geo_fullname,actor2_geo_country_code,actor2_geo_adm1_code,actor2_geo_lat,actor2_geo_lon,actor2_feature_id,action_geo_type,action_geo_fullname,action_geo_country_code,action_geo_adm1_code,action_geo_lat,action_geo_lon,action_feature_id,date_added,url_id,parse_date
0,61291642,420620763,2015-03-27,201503,2015,2015-03-27,20150327,USAMED,THE ASSOCIATED PRESS,USA,None,None,None,None,MED,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,164,164,16,4,-7.0,3,1,3,-0.264201,3,"Washington, District of Columbia, United States",US,USDC,38.8951,-77.0364,531871,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.388,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.388,-1898541,2015-03-27,None,2024-10-11 14:55:21.836254

In [4]:
service.get_file_by_date("20241001")

select * from file where id = '20241001'

,id,name,date,online_date,download_date,md5,dezip_date,import_start_date,import_end_date
0,20241001,20241001.export.CSV.zip,2024-10-01,2024-10-10 12:27:33.087136,2024-10-10 12:27:37.354428,aa566ba89b5348da7e76f85de2c5c9a4,2024-10-10 12:27:37.792179,2024-10-14 12:50:21.423071,2024-10-14 12:51:02.157264

In [5]:
service.get_files().head(5)

select * from file order by date desc

,id,name,date,online_date,download_date,md5,dezip_date,import_start_date,import_end_date
0,20241009,20241009.export.CSV.zip,2024-10-09,2024-10-10 12:28:10.185509,2024-10-10 12:28:14.425268,e60ba192ba84a3a88f0fc85d592d2c3b,2024-10-10 12:28:14.832299,2024-10-14 12:40:32.371037,2024-10-14 12:41:11.919210
1,20241008,20241008.export.CSV.zip,2024-10-08,2024-10-10 12:28:05.568595,2024-10-10 12:28:09.776177,7fd74d6c1741dc2030b7a1e4c55b25dd,2024-10-10 12:28:10.172054,2024-10-14 12:41:50.145194,2024-10-14 12:42:33.670737
2,20241007,20241007.export.CSV.zip,2024-10-07,2024-10-10 12:28:00.570065,2024-10-10 12:28:05.134301,6967c660ea29121868e77095ed5062a6,2024-10-10 12:28:05.568595,2024-10-14 12:43:12.135538,2024-10-14 12:43:51.302623
3,20241006,20241006.export.CSV.zip,2024-10-06,2024-10-10 12:27:58.680807,2024-10-10 12:28:00.355251,ae336ddc0b5614f0f3cb09beaff0f332,2024-10-10 12:28:00.570065,2024-10-14 12:44:23.236774,2024-10-14 12:44:57.690785
4,20241005,20241005.export.CSV.zip,2024-10-05,2024-10-10 12:27:54.471584,2024-10-10 12:27:58.431638,a8e8d2bbb70a9840a5b4a77823930b87,2024-10-10 12:27:58.653546,2024-10-14 12:45:17.357719,2024-10-14 12:45:52.184592

In [6]:
global_event_id = 420620763
events = service.get_by_global_event_id(global_event_id)
events

select * from event where global_event_id = 420620763

,id,global_event_id,date,month_year,year,gdelt_date,file_id,actor1_code,actor1_name,actor1_country_code,actor1_known_group_code,actor1_ethnic_code,actor1_religion1_code,actor1_religion2_code,actor1_type1_code,actor1_type2_code,actor1_type3_code,actor2_code,actor2_name,actor2_country_code,actor2_known_group_code,actor2_ethnic_code,actor2_religion1_code,actor2_religion2_code,actor2_type1_code,actor2_type2_code,actor2_type3_code,is_root_event,event_code,event_base_code,event_root_code,quad_class,goldstein_scale,num_mentions,num_sources,num_articles,avg_tone,actor1_geo_type,actor1_geo_fullname,actor1_geo_country_code,actor1_geo_adm1_code,actor1_geo_lat,actor1_geo_lon,actor1_feature_id,actor2_geo_type,actor2_geo_fullname,actor2_geo_country_code,actor2_geo_adm1_code,actor2_geo_lat,actor2_geo_lon,actor2_feature_id,action_geo_type,action_geo_fullname,action_geo_country_code,action_geo_adm1_code,action_geo_lat,action_geo_lon,action_feature_id,date_added,url_id,parse_date
0,61291642,420620763,2015-03-27,201503,2015,2015-03-27,20150327,USAMED,THE ASSOCIATED PRESS,USA,None,None,None,None,MED,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,164,164,16,4,-7.0,3,1,3,-0.264201,3,"Washington, District of Columbia, United States",US,USDC,38.8951,-77.0364,531871,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.388,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.388,-1898541,2015-03-27,None,2024-10-11 14:55:21.836254

In [7]:
res = service.get_by_year_month_country_codes(2015,2,'USA','CHN')
res.head(5)

select * from event where month_year = 201502 and actor1_country_code = 'USA' and actor2_country_code = 'CHN'

,id,global_event_id,date,month_year,year,gdelt_date,file_id,actor1_code,actor1_name,actor1_country_code,actor1_known_group_code,actor1_ethnic_code,actor1_religion1_code,actor1_religion2_code,actor1_type1_code,actor1_type2_code,actor1_type3_code,actor2_code,actor2_name,actor2_country_code,actor2_known_group_code,actor2_ethnic_code,actor2_religion1_code,actor2_religion2_code,actor2_type1_code,actor2_type2_code,actor2_type3_code,is_root_event,event_code,event_base_code,event_root_code,quad_class,goldstein_scale,num_mentions,num_sources,num_articles,avg_tone,actor1_geo_type,actor1_geo_fullname,actor1_geo_country_code,actor1_geo_adm1_code,actor1_geo_lat,actor1_geo_lon,actor1_feature_id,actor2_geo_type,actor2_geo_fullname,actor2_geo_country_code,actor2_geo_adm1_code,actor2_geo_lat,actor2_geo_lon,actor2_feature_id,action_geo_type,action_geo_fullname,action_geo_country_code,action_geo_adm1_code,action_geo_lat,action_geo_lon,action_feature_id,date_added,url_id,parse_date
0,60886988,421399575,2015-02-28,201502,2015,2015-03-30,20150330,MNCUSAMED,GOOGLE,USA,None,None,None,None,MNC,MED,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,False,172,172,17,4,-5.0,25,1,25,-3.486840,1,China,CH,CH,35.0000,105.000,CH,1,China,CH,CH,35.0000,105.000,CH,1,China,CH,CH,35.0000,105.000,CH,2015-03-30,None,2024-10-11 14:51:56.052561
1,60892785,421407577,2015-02-28,201502,2015,2015-03-30,20150330,MNCUSAMED,GOOGLE,USA,None,None,None,None,MNC,MED,None,CHN,CHINESE,CHN,None,None,None,None,None,None,None,False,192,192,19,4,-9.5,1,1,1,-5.828780,1,China,CH,CH,35.0000,105.000,CH,1,Hong Kong,HK,HK,22.2500,114.167,HK,1,China,CH,CH,35.0000,105.000,CH,2015-03-30,None,2024-10-11 14:51:56.584063
2,60886989,421399576,2015-02-28,201502,2015,2015-03-30,20150330,MNCUSAMED,GOOGLE,USA,None,None,None,None,MNC,MED,None,CHN,CHINESE,CHN,None,None,None,None,None,None,None,False,192,192,19,4,-9.5,24,1,24,-3.486840,1,China,CH,CH,35.0000,105.000,CH,1,China,CH,CH,35.0000,105.000,CH,1,China,CH,CH,35.0000,105.000,CH,2015-03-30,None,2024-10-11 14:51:56.052561
3,61506731,420297051,2015-02-24,201502,2015,2015-03-26,20150326,USA,SAN DIEGO,USA,None,None,None,None,None,None,None,CHNHLH,CHINESE,CHN,None,None,None,None,HLH,None,None,True,042,042,04,1,1.9,6,3,6,2.124942,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.388,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.388,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.388,-1898541,2015-03-26,None,2024-10-11 14:56:54.660507
4,61504652,420293919,2015-02-24,201502,2015,2015-03-26,20150326,USA,SAN DIEGO,USA,None,None,None,None,None,None,None,CHNHLH,CHINESE,CHN,None,None,None,None,HLH,None,None,True,043,043,04,1,2.8,7,1,7,2.144250,3,"San Diego, California, United States",US,USCA,32.7153,-117.157,1661377,3,"San Diego, California, United States",US,USCA,32.7153,-117.157,1661377,3,"San Diego, California, United States",US,USCA,32.7153,-117.157,1661377,2015-03-26,None,2024-10-11 14:56:54.457377

In [8]:
service.get_events_by_dates_country_codes(start_date="2015-02-01", end_date="2015-02-28", actor1_country_code="USA", actor2_country_code="CHN")

select * from event where date >= '2015-02-01' and date <= '2015-02-28' and is_root_event is true and actor1_country_code = 'USA' and actor2_country_code = 'CHN' and (actor1_type1_code = 'GOV' OR actor2_type1_code = 'GOV')

,id,global_event_id,date,month_year,year,gdelt_date,file_id,actor1_code,actor1_name,actor1_country_code,actor1_known_group_code,actor1_ethnic_code,actor1_religion1_code,actor1_religion2_code,actor1_type1_code,actor1_type2_code,actor1_type3_code,actor2_code,actor2_name,actor2_country_code,actor2_known_group_code,actor2_ethnic_code,actor2_religion1_code,actor2_religion2_code,actor2_type1_code,actor2_type2_code,actor2_type3_code,is_root_event,event_code,event_base_code,event_root_code,quad_class,goldstein_scale,num_mentions,num_sources,num_articles,avg_tone,actor1_geo_type,actor1_geo_fullname,actor1_geo_country_code,actor1_geo_adm1_code,actor1_geo_lat,actor1_geo_lon,actor1_feature_id,actor2_geo_type,actor2_geo_fullname,actor2_geo_country_code,actor2_geo_adm1_code,actor2_geo_lat,actor2_geo_lon,actor2_feature_id,action_geo_type,action_geo_fullname,action_geo_country_code,action_geo_adm1_code,action_geo_lat,action_geo_lon,action_feature_id,date_added,url_id,parse_date
0,62547145,418572753,2015-02-18,201502,2015,2015-03-20,20150320,USA,UNITED STATES,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,173,173,17,4,-5.0,54,8,50,-2.798779,3,"Chicago, Illinois, United States",US,USIL,41.8500,-87.6501,423587,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-03-20,None,2024-10-11 15:04:57.427377
1,62581204,418618267,2015-02-18,201502,2015,2015-03-20,20150320,USA,UNITED STATES,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,173,173,17,4,-5.0,5,1,5,-6.578947,1,United States,US,US,38.0000,-97.0000,US,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-03-20,None,2024-10-11 15:05:01.131839
2,62583782,418620845,2015-02-18,201502,2015,2015-03-20,20150320,USA,UNITED STATES,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,173,173,17,4,-5.0,20,3,20,-3.168586,1,United States,US,US,38.0000,-97.0000,US,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,2015-03-20,None,2024-10-11 15:05:01.382469
3,62613165,418661235,2015-02-18,201502,2015,2015-03-20,20150320,USA,THE US,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,173,173,17,4,-5.0,8,1,8,-6.250000,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,2015-03-20,None,2024-10-11 15:05:04.352279
4,66462775,413077833,2015-02-28,201502,2015,2015-02-28,20150228,USAELIGOVMIL,SUSAN E. RICE,USA,None,None,None,None,ELI,GOV,MIL,CHNGOV,YANG JIECHI,CHN,None,None,None,None,GOV,None,None,True,040,040,04,1,1.0,10,1,10,2.840909,2,"New York, United States",US,USNY,42.1497,-74.9384,NY,2,"New York, United States",US,USNY,42.1497,-74.9384,NY,2,"New York, United States",US,USNY,42.1497,-74.9384,NY,2015-02-28,None,2024-10-11 15:33:53.920359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,71141992,334753785,2015-02-01,201502,2015,2015-02-01,20150201,USAGOV,BARACK OBAMA,USA,None,None,None,None,GOV,None,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,013,013,01,1,0.4,2,1,2,3.170732,4,"New Delhi, Delhi, India",IN,IN07,28.6000,77.2000,-2106102,4,"New Delhi, Delhi, India",IN,IN07,28.6000,77.2000,-2106102,4,"New Delhi, Delhi, India",IN,IN07,28.6000,77.2000,-2106102,2015-02-01,None,2024-10-11 16:10:14.682123
815,71141994,334753787,2015-02-01,201502,2015,2015-02-01,20150201,USAGOV,OBAMA,USA,None,None,None,None,GOV,None,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,020,020,02,1,3.0,10,1,10,5.571031,3,"White House, District of Columbia, United States",US,USDC,38.8951,-77.0364,531871,3,"White House, District of Columbia, United States",US,USDC,38.8951,-77.0364,531871,3,"White House, District of Columbia, United States",US,USDC,38.8951,-77.0364,531871,2015-02-01,None,2024-10-11 16:10:14.682123
816,71141995,334753788,2015-02-01,201502,2015,2015-02-01,20150201,USAGOV,OBAMA,USA,None,None,None,None,GOV,None,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,020,020,02,1,3.0,10,1,10,5.571031,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,2015-02-01,None,2024-10-11 16:10:14.682123
817,71141996,334753789,2015-02-01,201502,2015,2015-02-01,20150201,USAGOV,OBAMA,USA,None,None,None,None,GOV,None,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,030,030,03,1,4.0,2,1,2,2.150538,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"New Delhi, Delhi, India",IN,IN07,28.6000,77.2000,-2106102,4,"New Delhi, Delhi, India",IN,IN07,28.6000,77.2000,-2106102,2015-02-01,None,2024-10-11 16:10:14.682123
818,71141997,334753790,2015-02-01,201502,2015,2015-02-01,20150201,USAGOV,OBAMA,USA,None,None,None,None,GOV,None,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,030,030,03,1,4.0,2,1,2,2.150538,4,"New Delhi, Delhi, India",IN,IN07,28.6000,77.2000,-2106102,4,"South China Sea, Brunei (general), Brunei",BX,BX00,15.0000,115.0000,-1337919,4,"South China Sea, Brunei (general), Brunei",BX,BX00,15.0000,115.0000,-1337919,2015-02-01,None,2024-10-11 16:10:14.682123

In [9]:
service.get_negative_events_by_dates_country_codes(start_date="2015-02-01", end_date="2015-02-28", actor1_country_code="USA", actor2_country_code="CHN")

select * from event where date >= '2015-02-01' and date <= '2015-02-28' and is_root_event is true and actor1_country_code = 'USA' and actor2_country_code = 'CHN' and (actor1_type1_code = 'GOV' OR actor2_type1_code = 'GOV') and quad_class >= 3 and goldstein_scale < 0 and avg_tone < 0

,id,global_event_id,date,month_year,year,gdelt_date,file_id,actor1_code,actor1_name,actor1_country_code,actor1_known_group_code,actor1_ethnic_code,actor1_religion1_code,actor1_religion2_code,actor1_type1_code,actor1_type2_code,actor1_type3_code,actor2_code,actor2_name,actor2_country_code,actor2_known_group_code,actor2_ethnic_code,actor2_religion1_code,actor2_religion2_code,actor2_type1_code,actor2_type2_code,actor2_type3_code,is_root_event,event_code,event_base_code,event_root_code,quad_class,goldstein_scale,num_mentions,num_sources,num_articles,avg_tone,actor1_geo_type,actor1_geo_fullname,actor1_geo_country_code,actor1_geo_adm1_code,actor1_geo_lat,actor1_geo_lon,actor1_feature_id,actor2_geo_type,actor2_geo_fullname,actor2_geo_country_code,actor2_geo_adm1_code,actor2_geo_lat,actor2_geo_lon,actor2_feature_id,action_geo_type,action_geo_fullname,action_geo_country_code,action_geo_adm1_code,action_geo_lat,action_geo_lon,action_feature_id,date_added,url_id,parse_date
0,62547145,418572753,2015-02-18,201502,2015,2015-03-20,20150320,USA,UNITED STATES,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,173,173,17,4,-5.0,54,8,50,-2.798779,3,"Chicago, Illinois, United States",US,USIL,41.8500,-87.6501,423587,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-03-20,None,2024-10-11 15:04:57.427377
1,62583782,418620845,2015-02-18,201502,2015,2015-03-20,20150320,USA,UNITED STATES,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,173,173,17,4,-5.0,20,3,20,-3.168586,1,United States,US,US,38.0000,-97.0000,US,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,2015-03-20,None,2024-10-11 15:05:01.382469
2,62581204,418618267,2015-02-18,201502,2015,2015-03-20,20150320,USA,UNITED STATES,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,173,173,17,4,-5.0,5,1,5,-6.578947,1,United States,US,US,38.0000,-97.0000,US,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-03-20,None,2024-10-11 15:05:01.131839
3,66431718,413033750,2015-02-28,201502,2015,2015-02-28,20150228,USAGOV,US OFFICIAL,USA,None,None,None,None,GOV,None,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,111,111,11,3,-2.0,25,5,25,-4.109589,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-02-28,None,2024-10-11 15:33:50.761111
4,62613165,418661235,2015-02-18,201502,2015,2015-03-20,20150320,USA,THE US,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,173,173,17,4,-5.0,8,1,8,-6.250000,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,2015-03-20,None,2024-10-11 15:05:04.352279
5,62668522,418748505,2015-02-18,201502,2015,2015-03-20,20150320,USA,UNITED STATES,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,173,173,17,4,-5.0,5,1,5,-3.076923,3,"Washington, District of Columbia, United States",US,USDC,38.8951,-77.0364,531871,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,2015-03-20,None,2024-10-11 15:05:10.229920
6,66421972,413020194,2015-02-28,201502,2015,2015-02-28,20150228,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,XINJIANG,CHN,None,None,None,None,None,None,None,True,1831,183,18,4,-10.0,10,1,10,-6.709265,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,2015-02-28,None,2024-10-11 15:33:49.728862
7,66574621,412743646,2015-02-27,201502,2015,2015-02-27,20150227,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,XINJIANG,CHN,None,None,None,None,None,None,None,True,1831,183,18,4,-10.0,30,3,30,-5.451427,4,"Kunming, Yunnan, China",CH,CH29,25.0389,102.7180,-1913826,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,2015-02-27,None,2024-10-11 15:34:59.025503
8,66460079,413073619,2015-02-28,201502,2015,2015-02-28,20150228,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,XINJIANG,CHN,None,None,None,None,None,None,None,True,1831,183,18,4,-10.0,40,2,40,-5.098235,4,"Kunming, Yunnan, China",CH,CH29,25.0389,102.7180,-1913826,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,2015-02-28,None,2024-10-11 15:33:53.560594
9,66830366,412479477,2015-02-26,201502,2015,2015-02-26,20150226,USAGOV,HILLARY CLINTON,USA,None,None,None,None,GOV,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,172,172,17,4,-5.0,10,1,10,-1.717557,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-02-26,None,2024-10-11 15:36:37.378111
10,66830367,412479478,2015-02-26,201502,2015,2015-02-26,20150226,USAGOV,HILLARY CLINTON,USA,None,None,None,None,GOV,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,172,172,17,4,-5.0,6,1,6,-1.717557,3,"Washington, District of Columbia, United States",US,USDC,38.8951,-77.0364,531871,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-02-26,None,2024-10-11 15:36:37.378111
11,66904564,412598258,2015-02-26,201502,2015,2015-02-26,20150226,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,XINJIANG,CHN,None,None,None,None,None,None,None,True,1831,183,18,4,-10.0,10,1,10,-5.831533,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,2015-02-26,None,2024-10-11 15:36:45.384687
12,66939981,412650327,2015-02-26,201502,2015,2015-02-26,20150226,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,XINJIANG,CHN,None,None,None,None,None,None,None,True,1831,183,18,4,-10.0,10,1,10,-5.498282,4,"Kunming, Yunnan, China",CH,CH29,25.0389,102.7180,-1913826,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,2015-02-26,None,2024-10-11 15:36:48.919527
13,66911484,412608954,2015-02-26,201502,2015,2015-02-26,20150226,MNCUSA,MICROSOFT,USA,None,None,None,None,MNC,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,160,160,16,4,-4.0,5,1,5,-2.086957,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-02-26,None,2024-10-11 15:36:46.135153
14,66911485,412608955,2015-02-26,201502,2015,2015-02-26,20150226,MNCUSA,MICROSOFT,USA,None,None,None,None,MNC,None,None,CHNGOV,CHINA,CHN,None,None,None,None,GOV,None,None,True,160,160,16,4,-4.0,1,1,1,-2.086957,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Bangkok, Krung Thep Mahanakhon, Thailand",TH,TH40,13.7500,100.5170,-3250083,4,"Bangkok, Krung Thep Mahanakhon, Thailand",TH,TH40,13.7500,100.5170,-3250083,2015-02-26,None,2024-10-11 15:36:46.135153
15,66911486,412608956,2015-02-26,201502,2015,2015-02-26,20150226,MNCUSA,MICROSOFT,USA,None,None,None,None,MNC,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,160,160,16,4,-4.0,4,1,4,-2.086957,4,"Bangkok, Krung Thep Mahanakhon, Thailand",TH,TH40,13.7500,100.5170,-3250083,4,"Bangkok, Krung Thep Mahanakhon, Thailand",TH,TH40,13.7500,100.5170,-3250083,4,"Bangkok, Krung Thep Mahanakhon, Thailand",TH,TH40,13.7500,100.5170,-3250083,2015-02-26,None,2024-10-11 15:36:46.135153
16,66969936,412692137,2015-02-26,201502,2015,2015-02-26,20150226,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,CHINESE,CHN,None,None,None,None,None,None,None,True,172,172,17,4,-5.0,5,1,5,-6.701031,4,"Nansan, Guangdong, China",CH,CH30,21.1489,110.5540,6024159,4,"Nansan, Guangdong, China",CH,CH30,21.1489,110.5540,6024159,4,"Nansan, Guangdong, China",CH,CH30,21.1489,110.5540,6024159,2015-02-26,None,2024-10-11 15:36:52.266248
17,67031990,412121031,2015-02-25,201502,2015,2015-02-25,20150225,USAGOV,NASA,USA,None,None,None,None,GOV,None,None,CHN,CHINESE,CHN,None,None,None,None,None,None,None,True,120,120,12,3,-4.0,23,2,23,-1.612470,1,Canada,CA,CA,60.0000,-95.0000,CA,1,Canada,CA,CA,60.0000,-95.0000,CA,1,Canada,CA,CA,60.0000,-95.0000,CA,2015-02-25,None,2024-10-11 15:38:14.340380
18,67051181,412147376,2015-02-25,201502,2015,2015-02-25,20150225,USAGOV,NASA,USA,None,None,None,None,GOV,None,None,CHN,CHINESE,CHN,None,None,None,None,None,None,None,True,120,120,12,3,-4.0,1,1,1,-2.083333,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,2015-02-25,None,2024-10-11 15:38:16.185610
19,67198876,412372224,2015-02-25,201502,2015,2015-02-25,20150225,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,XINJIANG,CHN,None,None,None,None,None,None,None,True,1831,183,18,4,-10.0,10,1,10,-5.078809,4,"Kunming, Yunnan, China",CH,CH29,25.0389,102.7180,-1913826,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,4,"Xinjiang, Jiangxi, China",CH,CH03,27.7481,116.2740,11065838,2015-02-25,None,2024-10-11 15:38:31.778372
20,67398522,412021979,2015-02-24,201502,2015,2015-02-24,20150224,USAGOVLEG,JOHN BOEHNER,USA,None,None,None,None,GOV,LEG,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,129,129,12,3,-5.0,8,1,8,-4.897959,1,Russia,RS,RS,60.0000,100.0000,RS,1,China,CH,CH,35.0000,105.0000,CH,1,Russia,RS,RS,60.0000,100.0000,RS,2015-02-24,None,2024-10-11 15:40:09.475235
21,67398523,412021980,2015-02-24,201502,2015,2015-02-24,20150224,USAGOVLEG,JOHN BOEHNER,USA,None,None,None,None,GOV,LEG,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,129,129,12,3,-5.0,2,1,2,-4.897959,1,Russia,RS,RS,60.0000,100.0000,RS,1,Russia,RS,RS,60.0000,100.0000,RS,1,Russia,RS,RS,60.0000,100.0000,RS,2015-02-24,None,2024-10-11 15:40:09.475235
22,67682925,411357895,2015-02-22,201502,2015,2015-02-22,20150222,USAGOV,OBAMA,USA,None,None,None,None,GOV,None,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,112,112,11,3,-2.0,2,1,2,-4.231626,3,"The White House, District of Columbia, United ...",US,USDC,38.8951,-77.0364,531871,3,"The White House, District of Columbia, United ...",US,USDC,38.8951,-77.0364,531871,3,"The White House, District of Columbia, United ...",US,USDC,38.8951,-77.0364,531871,2015-02-22,None,2024-10-11 15:42:59.154179
23,67682926,411357896,2015-02-22,201502,2015,2015-02-22,20150222,USAGOV,OBAMA,USA,None,None,None,None,GOV,None,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,112,112,11,3,-2.0,8,1,8,-4.231626,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,2015-02-22,None,2024-10-11 15:42:59.154179
24,67803451,411143074,2015-02-21,201502,2015,2015-02-21,20150221,USA,SAN DIEGO,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,110,110,11,3,-2.0,3,1,3,-4.564315,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-02-21,None,2024-10-11 15:44:01.717217
25,68083303,410435219,2015-02-19,201502,2015,2015-02-19,20150219,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,CHINESE,CHN,None,None,None,None,None,None,None,True,190,190,19,4,-10.0,7,1,7,-6.886228,4,"Pishan, Chongqing, China",CH,CH33,29.5956,106.2240,-1898979,4,"Pishan, Chongqing, China",CH,CH33,29.5956,106.2240,-1898979,4,"Pishan, Chongqing, China",CH,CH33,29.5956,106.2240,-1898979,2015-02-19,None,2024-10-11 15:46:35.238652
26,67946882,410849157,2015-02-20,201502,2015,2015-02-20,20150220,USA,SAN DIEGO,USA,None,None,None,None,None,None,None,CHNGOV,CHINESE,CHN,None,None,None,None,GOV,None,None,True,110,110,11,3,-2.0,3,1,3,-4.564315,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,4,"Beijing, Beijing, China",CH,CH22,39.9289,116.3880,-1898541,2015-02-20,None,2024-10-11 15:45:09.766014
27,67969151,410885009,2015-02-20,201502,2015,2015-02-20,20150220,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,192,192,19,4,-9.5,2,1,2,-5.932203,4,"Zhenkang, Yunnan, China",CH,CH29,23.7957,98.8040,-1905465,4,"Zhenkang, Yunnan, China",CH,CH29,23.7957,98.8040,-1905465,4,"Zhenkang, Yunnan, China",CH,CH29,23.7957,98.8040,-1905465,2015-02-20,None,2024-10-11 15:45:12.095484
28,68093816,410449978,2015-02-19,201502,2015,2015-02-19,20150219,USAGOV,OBAMA,USA,None,None,None,None,GOV,None,None,CHN,CHINA,CHN,None,None,None,None,None,None,None,True,120,120,12,3,-4.0,5,1,5,-0.450958,2,"West Virginia, United States",US,USWV,38.4680,-80.9696,WV,1,China,CH,CH,35.0000,105.0000,CH,1,China,CH,CH,35.0000,105.0000,CH,2015-02-19,None,2024-10-11 15:46:36.192326
29,68506843,410420417,2015-02-18,201502,2015,2015-02-18,20150218,USAGOVMEDASA,RADIO FREE ASIA,USA,None,None,None,None,GOV,MED,None,CHN,CHINESE,CHN,None,None,None,None,None,None,None,True,190,190,19,4,-10.0,7,1,7,-6.886228,4,"Pishan, Chongqing, China",CH,CH33,29.5956,106.2240,-1898979,4,"Pishan, Chongqing, China",CH,CH33,29.5956,106.2240,-1898979,4,"Pishan, Chongqing, China",CH,CH33,29.5956,106.2240,-1898979,2015-02-18,None,2024-10-11 15:48:31.822671

In [10]:
service.get_risks_by_dates_codes(start_date='2015-02-01', end_date='2015-02-28', actor1_code='USA', actor2_code='CHN')

select * from daily_risk where date >= '2015-02-01' and date <= '2015-02-28' and actor1_code = 'USA' and actor2_code = 'CHN'

,id,date,actor1_code,actor2_code,quad3_nb,quad4_nb,total_nb,article3_nb,article4_nb,total_article_nb,compute_date
0,120,2015-02-18,USA,CHN,0.0,6.0,20.0,0.0,95.0,169.0,2024-10-16 11:19:12.133005
1,352,2015-02-19,USA,CHN,1.0,1.0,13.0,5.0,7.0,162.0,2024-10-16 11:19:12.443559
2,538,2015-02-20,USA,CHN,1.0,1.0,12.0,3.0,2.0,93.0,2024-10-16 11:19:12.789939
3,679,2015-02-21,USA,CHN,1.0,0.0,9.0,3.0,0.0,40.0,2024-10-16 11:19:13.032656
4,837,2015-02-22,USA,CHN,2.0,0.0,4.0,10.0,0.0,23.0,2024-10-16 11:19:13.242650
5,1087,2015-02-24,USA,CHN,2.0,0.0,33.0,10.0,0.0,942.0,2024-10-16 11:19:13.990214
6,1256,2015-02-25,USA,CHN,2.0,1.0,16.0,24.0,10.0,297.0,2024-10-16 11:19:14.385899
7,1460,2015-02-26,USA,CHN,0.0,8.0,20.0,0.0,51.0,167.0,2024-10-16 11:19:14.835584
8,1634,2015-02-27,USA,CHN,0.0,1.0,15.0,0.0,30.0,467.0,2024-10-16 11:19:15.256644
9,1780,2015-02-28,USA,CHN,1.0,2.0,12.0,25.0,50.0,205.0,2024-10-16 11:19:15.552607

In [11]:
service.get_iscris_by_year_month(year=2015, month=2)

select * from iscri where year = 2015 and month = 2

,id,year,month,actor1_code,actor2_code,risk,risk3,risk4,risk_date,iscri,iscri3,iscri4,iscri_date
0,29683,2015,2,IDN,NGA,0.071429,0.071429,0.000000,2024-10-17 15:15:15.621572,0.071429,0.071429,0.000000,2024-10-17 15:19:17.226293
1,29684,2015,2,SAU,JOR,0.028912,0.000000,0.028912,2024-10-17 15:15:15.621572,0.028912,0.000000,0.028912,2024-10-17 15:19:17.226293
2,29685,2015,2,CHE,YEM,0.071429,0.000000,0.071429,2024-10-17 15:15:15.621572,0.071429,0.000000,0.071429,2024-10-17 15:19:17.226293
3,29686,2015,2,TUR,YEM,0.035714,0.000000,0.035714,2024-10-17 15:15:15.621572,0.035714,0.000000,0.035714,2024-10-17 15:19:17.226293
4,29687,2015,2,USA,BEL,0.035714,0.035714,0.000000,2024-10-17 15:15:15.621572,0.035714,0.035714,0.000000,2024-10-17 15:19:17.226293
...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,44494,2015,2,GHA,NGA,0.000000,0.000000,0.000000,2024-10-17 15:19:02.134944,0.017419,0.017419,0.000000,2024-10-17 15:19:17.234641
815,44495,2015,2,USA,IND,0.000000,0.000000,0.000000,2024-10-17 15:19:02.134944,0.000968,0.000000,0.000968,2024-10-17 15:19:17.234641
816,44496,2015,2,IND,MDV,0.000000,0.000000,0.000000,2024-10-17 15:19:02.135939,0.029032,0.000000,0.029032,2024-10-17 15:19:17.234641
817,44497,2015,2,AUS,CAN,0.000000,0.000000,0.000000,2024-10-17 15:19:02.135939,0.029032,0.000000,0.029032,2024-10-17 15:19:17.234641
818,44498,2015,2,CAN,AUS,0.000000,0.000000,0.000000,2024-10-17 15:19:02.135939,0.029032,0.000000,0.029032,2024-10-17 15:19:17.234641

In [12]:
service.get_iscris_by_codes(actor1_code='USA', actor2_code='CHN')

select * from iscri where actor1_code = 'USA' and actor2_code = 'CHN' order by year, month

,id,year,month,actor1_code,actor2_code,risk,risk3,risk4,risk_date,iscri,iscri3,iscri4,iscri_date
0,44493,2015,1,USA,CHN,0.000000,0.000000,0.000000,2024-10-17 15:18:36.929878,1.570000,0.000000,0.000000,2024-10-17 15:18:36.929878
1,29745,2015,2,USA,CHN,0.078443,0.037154,0.041289,2024-10-17 15:15:15.621572,1.491443,0.037154,0.041289,2024-10-17 15:19:17.226293
2,30520,2015,3,USA,CHN,0.167253,0.124861,0.042392,2024-10-17 15:15:16.029373,1.509552,0.158300,0.079552,2024-10-18 09:02:55.371367
3,32007,2015,4,USA,CHN,0.157135,0.137533,0.019602,2024-10-17 15:15:16.750873,1.515732,0.280002,0.091199,2024-10-18 09:02:55.734416
4,33710,2015,5,USA,CHN,0.134733,0.097610,0.037122,2024-10-17 15:15:17.440587,1.498891,0.349612,0.119202,2024-10-18 09:02:56.207691
5,34916,2015,6,USA,CHN,0.252236,0.231594,0.020642,2024-10-17 15:15:18.120678,1.601238,0.546245,0.127923,2024-10-18 09:02:56.635900
6,36333,2015,7,USA,CHN,0.191774,0.154580,0.037194,2024-10-17 15:15:18.792846,1.632888,0.646200,0.152325,2024-10-18 09:02:57.050355
7,37652,2015,8,USA,CHN,0.175818,0.084766,0.091052,2024-10-17 15:15:19.456561,1.645417,0.666346,0.228145,2024-10-18 09:02:57.516385
8,39005,2015,9,USA,CHN,0.102165,0.075293,0.026873,2024-10-17 15:15:20.110211,1.583040,0.675004,0.232203,2024-10-18 09:02:58.004363
9,40427,2015,10,USA,CHN,0.109846,0.060300,0.049546,2024-10-17 15:15:20.784986,1.534582,0.667804,0.258528,2024-10-18 09:02:58.486447
10,41871,2015,11,USA,CHN,0.096924,0.077327,0.019596,2024-10-17 15:15:21.450024,1.478048,0.678351,0.252272,2024-10-18 09:02:59.020982
11,43242,2015,12,USA,CHN,0.121220,0.106305,0.014915,2024-10-17 15:15:22.135488,1.451463,0.716821,0.241959,2024-10-18 09:02:59.591234

In [13]:
service.get_iscris_by_dates_codes(start_year=2015, start_month=1, end_year=2015, end_month=7, actor1_code='USA', actor2_code='CHN')

select * from iscri where actor1_code = 'USA' and actor2_code = 'CHN' and year * 100 + month >= 201501 and year * 100 + month <= 201507 order by year, month

,id,year,month,actor1_code,actor2_code,risk,risk3,risk4,risk_date,iscri,iscri3,iscri4,iscri_date
0,44493,2015,1,USA,CHN,0.000000,0.000000,0.000000,2024-10-17 15:18:36.929878,1.570000,0.000000,0.000000,2024-10-17 15:18:36.929878
1,29745,2015,2,USA,CHN,0.078443,0.037154,0.041289,2024-10-17 15:15:15.621572,1.491443,0.037154,0.041289,2024-10-17 15:19:17.226293
2,30520,2015,3,USA,CHN,0.167253,0.124861,0.042392,2024-10-17 15:15:16.029373,1.509552,0.158300,0.079552,2024-10-18 09:02:55.371367
3,32007,2015,4,USA,CHN,0.157135,0.137533,0.019602,2024-10-17 15:15:16.750873,1.515732,0.280002,0.091199,2024-10-18 09:02:55.734416
4,33710,2015,5,USA,CHN,0.134733,0.097610,0.037122,2024-10-17 15:15:17.440587,1.498891,0.349612,0.119202,2024-10-18 09:02:56.207691
5,34916,2015,6,USA,CHN,0.252236,0.231594,0.020642,2024-10-17 15:15:18.120678,1.601238,0.546245,0.127923,2024-10-18 09:02:56.635900
6,36333,2015,7,USA,CHN,0.191774,0.154580,0.037194,2024-10-17 15:15:18.792846,1.632888,0.646200,0.152325,2024-10-18 09:02:57.050355